# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jiecao/Documents/code/satifs/satifs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jiecao/Documents/code/satifs/satifs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jiecao/Documents/code/satifs/satifs/CMakeFiles /Users/jiecao/Documents/code/satifs/satifs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jiecao/Documents/code/satifs/satifs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named satifs_client

# Build rule for target.
satifs_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 satifs_client
.PHONY : satifs_client

# fast build rule for target.
satifs_client/fast:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/build
.PHONY : satifs_client/fast

#=============================================================================
# Target rules for targets named satifs_test

# Build rule for target.
satifs_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 satifs_test
.PHONY : satifs_test

# fast build rule for target.
satifs_test/fast:
	$(MAKE) -f CMakeFiles/satifs_test.dir/build.make CMakeFiles/satifs_test.dir/build
.PHONY : satifs_test/fast

#=============================================================================
# Target rules for targets named satifs_server

# Build rule for target.
satifs_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 satifs_server
.PHONY : satifs_server

# fast build rule for target.
satifs_server/fast:
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/build
.PHONY : satifs_server/fast

#=============================================================================
# Target rules for targets named SATIFS_SERVER_LIB

# Build rule for target.
SATIFS_SERVER_LIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SATIFS_SERVER_LIB
.PHONY : SATIFS_SERVER_LIB

# fast build rule for target.
SATIFS_SERVER_LIB/fast:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/build
.PHONY : SATIFS_SERVER_LIB/fast

counter.pb.o: counter.pb.cc.o

.PHONY : counter.pb.o

# target to build an object file
counter.pb.cc.o:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/counter.pb.cc.o
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/counter.pb.cc.o
.PHONY : counter.pb.cc.o

counter.pb.i: counter.pb.cc.i

.PHONY : counter.pb.i

# target to preprocess a source file
counter.pb.cc.i:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/counter.pb.cc.i
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/counter.pb.cc.i
.PHONY : counter.pb.cc.i

counter.pb.s: counter.pb.cc.s

.PHONY : counter.pb.s

# target to generate assembly for a file
counter.pb.cc.s:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/counter.pb.cc.s
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/counter.pb.cc.s
.PHONY : counter.pb.cc.s

echo.pb.o: echo.pb.cc.o

.PHONY : echo.pb.o

# target to build an object file
echo.pb.cc.o:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/echo.pb.cc.o
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/echo.pb.cc.o
.PHONY : echo.pb.cc.o

echo.pb.i: echo.pb.cc.i

.PHONY : echo.pb.i

# target to preprocess a source file
echo.pb.cc.i:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/echo.pb.cc.i
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/echo.pb.cc.i
.PHONY : echo.pb.cc.i

echo.pb.s: echo.pb.cc.s

.PHONY : echo.pb.s

# target to generate assembly for a file
echo.pb.cc.s:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/echo.pb.cc.s
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/echo.pb.cc.s
.PHONY : echo.pb.cc.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/satifs_server.dir/build.make CMakeFiles/satifs_server.dir/main.cpp.s
.PHONY : main.cpp.s

src/client/client.o: src/client/client.cpp.o

.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i

.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s

.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) -f CMakeFiles/satifs_client.dir/build.make CMakeFiles/satifs_client.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/server/block_management/block_info.o: src/server/block_management/block_info.cpp.o

.PHONY : src/server/block_management/block_info.o

# target to build an object file
src/server/block_management/block_info.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/block_management/block_info.cpp.o
.PHONY : src/server/block_management/block_info.cpp.o

src/server/block_management/block_info.i: src/server/block_management/block_info.cpp.i

.PHONY : src/server/block_management/block_info.i

# target to preprocess a source file
src/server/block_management/block_info.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/block_management/block_info.cpp.i
.PHONY : src/server/block_management/block_info.cpp.i

src/server/block_management/block_info.s: src/server/block_management/block_info.cpp.s

.PHONY : src/server/block_management/block_info.s

# target to generate assembly for a file
src/server/block_management/block_info.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/block_management/block_info.cpp.s
.PHONY : src/server/block_management/block_info.cpp.s

src/server/block_management/datanode_storage_info.o: src/server/block_management/datanode_storage_info.cpp.o

.PHONY : src/server/block_management/datanode_storage_info.o

# target to build an object file
src/server/block_management/datanode_storage_info.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/block_management/datanode_storage_info.cpp.o
.PHONY : src/server/block_management/datanode_storage_info.cpp.o

src/server/block_management/datanode_storage_info.i: src/server/block_management/datanode_storage_info.cpp.i

.PHONY : src/server/block_management/datanode_storage_info.i

# target to preprocess a source file
src/server/block_management/datanode_storage_info.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/block_management/datanode_storage_info.cpp.i
.PHONY : src/server/block_management/datanode_storage_info.cpp.i

src/server/block_management/datanode_storage_info.s: src/server/block_management/datanode_storage_info.cpp.s

.PHONY : src/server/block_management/datanode_storage_info.s

# target to generate assembly for a file
src/server/block_management/datanode_storage_info.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/block_management/datanode_storage_info.cpp.s
.PHONY : src/server/block_management/datanode_storage_info.cpp.s

src/server/ha/raft_service.o: src/server/ha/raft_service.cpp.o

.PHONY : src/server/ha/raft_service.o

# target to build an object file
src/server/ha/raft_service.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/ha/raft_service.cpp.o
.PHONY : src/server/ha/raft_service.cpp.o

src/server/ha/raft_service.i: src/server/ha/raft_service.cpp.i

.PHONY : src/server/ha/raft_service.i

# target to preprocess a source file
src/server/ha/raft_service.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/ha/raft_service.cpp.i
.PHONY : src/server/ha/raft_service.cpp.i

src/server/ha/raft_service.s: src/server/ha/raft_service.cpp.s

.PHONY : src/server/ha/raft_service.s

# target to generate assembly for a file
src/server/ha/raft_service.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/ha/raft_service.cpp.s
.PHONY : src/server/ha/raft_service.cpp.s

src/server/main_server.o: src/server/main_server.cpp.o

.PHONY : src/server/main_server.o

# target to build an object file
src/server/main_server.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/main_server.cpp.o
.PHONY : src/server/main_server.cpp.o

src/server/main_server.i: src/server/main_server.cpp.i

.PHONY : src/server/main_server.i

# target to preprocess a source file
src/server/main_server.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/main_server.cpp.i
.PHONY : src/server/main_server.cpp.i

src/server/main_server.s: src/server/main_server.cpp.s

.PHONY : src/server/main_server.s

# target to generate assembly for a file
src/server/main_server.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/main_server.cpp.s
.PHONY : src/server/main_server.cpp.s

src/server/namenode/inode.o: src/server/namenode/inode.cpp.o

.PHONY : src/server/namenode/inode.o

# target to build an object file
src/server/namenode/inode.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode.cpp.o
.PHONY : src/server/namenode/inode.cpp.o

src/server/namenode/inode.i: src/server/namenode/inode.cpp.i

.PHONY : src/server/namenode/inode.i

# target to preprocess a source file
src/server/namenode/inode.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode.cpp.i
.PHONY : src/server/namenode/inode.cpp.i

src/server/namenode/inode.s: src/server/namenode/inode.cpp.s

.PHONY : src/server/namenode/inode.s

# target to generate assembly for a file
src/server/namenode/inode.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode.cpp.s
.PHONY : src/server/namenode/inode.cpp.s

src/server/namenode/inode_attributes.o: src/server/namenode/inode_attributes.cpp.o

.PHONY : src/server/namenode/inode_attributes.o

# target to build an object file
src/server/namenode/inode_attributes.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_attributes.cpp.o
.PHONY : src/server/namenode/inode_attributes.cpp.o

src/server/namenode/inode_attributes.i: src/server/namenode/inode_attributes.cpp.i

.PHONY : src/server/namenode/inode_attributes.i

# target to preprocess a source file
src/server/namenode/inode_attributes.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_attributes.cpp.i
.PHONY : src/server/namenode/inode_attributes.cpp.i

src/server/namenode/inode_attributes.s: src/server/namenode/inode_attributes.cpp.s

.PHONY : src/server/namenode/inode_attributes.s

# target to generate assembly for a file
src/server/namenode/inode_attributes.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_attributes.cpp.s
.PHONY : src/server/namenode/inode_attributes.cpp.s

src/server/namenode/inode_directory.o: src/server/namenode/inode_directory.cpp.o

.PHONY : src/server/namenode/inode_directory.o

# target to build an object file
src/server/namenode/inode_directory.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_directory.cpp.o
.PHONY : src/server/namenode/inode_directory.cpp.o

src/server/namenode/inode_directory.i: src/server/namenode/inode_directory.cpp.i

.PHONY : src/server/namenode/inode_directory.i

# target to preprocess a source file
src/server/namenode/inode_directory.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_directory.cpp.i
.PHONY : src/server/namenode/inode_directory.cpp.i

src/server/namenode/inode_directory.s: src/server/namenode/inode_directory.cpp.s

.PHONY : src/server/namenode/inode_directory.s

# target to generate assembly for a file
src/server/namenode/inode_directory.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_directory.cpp.s
.PHONY : src/server/namenode/inode_directory.cpp.s

src/server/namenode/inode_file.o: src/server/namenode/inode_file.cpp.o

.PHONY : src/server/namenode/inode_file.o

# target to build an object file
src/server/namenode/inode_file.cpp.o:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_file.cpp.o
.PHONY : src/server/namenode/inode_file.cpp.o

src/server/namenode/inode_file.i: src/server/namenode/inode_file.cpp.i

.PHONY : src/server/namenode/inode_file.i

# target to preprocess a source file
src/server/namenode/inode_file.cpp.i:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_file.cpp.i
.PHONY : src/server/namenode/inode_file.cpp.i

src/server/namenode/inode_file.s: src/server/namenode/inode_file.cpp.s

.PHONY : src/server/namenode/inode_file.s

# target to generate assembly for a file
src/server/namenode/inode_file.cpp.s:
	$(MAKE) -f CMakeFiles/SATIFS_SERVER_LIB.dir/build.make CMakeFiles/SATIFS_SERVER_LIB.dir/src/server/namenode/inode_file.cpp.s
.PHONY : src/server/namenode/inode_file.cpp.s

src/test/inode_file_test.o: src/test/inode_file_test.cpp.o

.PHONY : src/test/inode_file_test.o

# target to build an object file
src/test/inode_file_test.cpp.o:
	$(MAKE) -f CMakeFiles/satifs_test.dir/build.make CMakeFiles/satifs_test.dir/src/test/inode_file_test.cpp.o
.PHONY : src/test/inode_file_test.cpp.o

src/test/inode_file_test.i: src/test/inode_file_test.cpp.i

.PHONY : src/test/inode_file_test.i

# target to preprocess a source file
src/test/inode_file_test.cpp.i:
	$(MAKE) -f CMakeFiles/satifs_test.dir/build.make CMakeFiles/satifs_test.dir/src/test/inode_file_test.cpp.i
.PHONY : src/test/inode_file_test.cpp.i

src/test/inode_file_test.s: src/test/inode_file_test.cpp.s

.PHONY : src/test/inode_file_test.s

# target to generate assembly for a file
src/test/inode_file_test.cpp.s:
	$(MAKE) -f CMakeFiles/satifs_test.dir/build.make CMakeFiles/satifs_test.dir/src/test/inode_file_test.cpp.s
.PHONY : src/test/inode_file_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... satifs_client"
	@echo "... satifs_test"
	@echo "... satifs_server"
	@echo "... rebuild_cache"
	@echo "... SATIFS_SERVER_LIB"
	@echo "... counter.pb.o"
	@echo "... counter.pb.i"
	@echo "... counter.pb.s"
	@echo "... echo.pb.o"
	@echo "... echo.pb.i"
	@echo "... echo.pb.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/server/block_management/block_info.o"
	@echo "... src/server/block_management/block_info.i"
	@echo "... src/server/block_management/block_info.s"
	@echo "... src/server/block_management/datanode_storage_info.o"
	@echo "... src/server/block_management/datanode_storage_info.i"
	@echo "... src/server/block_management/datanode_storage_info.s"
	@echo "... src/server/ha/raft_service.o"
	@echo "... src/server/ha/raft_service.i"
	@echo "... src/server/ha/raft_service.s"
	@echo "... src/server/main_server.o"
	@echo "... src/server/main_server.i"
	@echo "... src/server/main_server.s"
	@echo "... src/server/namenode/inode.o"
	@echo "... src/server/namenode/inode.i"
	@echo "... src/server/namenode/inode.s"
	@echo "... src/server/namenode/inode_attributes.o"
	@echo "... src/server/namenode/inode_attributes.i"
	@echo "... src/server/namenode/inode_attributes.s"
	@echo "... src/server/namenode/inode_directory.o"
	@echo "... src/server/namenode/inode_directory.i"
	@echo "... src/server/namenode/inode_directory.s"
	@echo "... src/server/namenode/inode_file.o"
	@echo "... src/server/namenode/inode_file.i"
	@echo "... src/server/namenode/inode_file.s"
	@echo "... src/test/inode_file_test.o"
	@echo "... src/test/inode_file_test.i"
	@echo "... src/test/inode_file_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

